apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hstop0mij-go 
  janus-idp.io/tekton: hstop0mij-go
  backstage.io/kubernetes-id: hstop0mij-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hstop0mij-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml